name: Continuous Integration

on:
  pull_request:
  push:
    branches-ignore:
      - main
      - angular-legacy
      - nextjs-legacy

jobs:
  Build:
    name: Build Nuxt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v5
      - name: Use Node.js v20
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: yarn
          registry-url: https://registry.yarnpkg.com/
      - name: Install Dependencies
        run: yarn --immutable
      - name: Build Nuxt
        run: yarn build

  FormatCheck:
    name: Prettier Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v5
      - name: Use Node.js v20
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: yarn
          registry-url: https://registry.yarnpkg.com/
      - name: Install Dependencies
        run: yarn --immutable
      - name: Prettier Check
        run: yarn format:check
